export { default as EditorialHero } from './editorial-hero'
export { default as EditorialDescriptionSection } from './editorial-description'
export { default as EditorialSectionOne } from './editorial-section-one'
export { default as EditorialSectionTwo } from './editorial-section-two'
export { default as EditorialImgSection } from './editorial-img-section'
export { default as EditorialsRelated } from './editorials-related'
export { default as EditorialOmnySection } from './editorial-omny-player'